config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :home, :profiles, :bleats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bleat.rb
class Bleat < ApplicationRecord
  belongs_to :user, dependent: :destroy
  validates :body, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :email, presence: true
  has_many :bleats
  attr_writer :login
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/bleats_controller.rb
class BleatsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @bleat = current_user.bleats.build
  end

  def create
    @bleat = current_user.bleats.build(bleat_params)
    if @bleat.save
      redirect_to profile_path(current_user.id)
    else
      render :new
    end
  end

  # def index
  #  @bleats = Bleat.all
  # end

  private

  def bleat_params
    params.require(:bleat).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @bleats = Bleat.all
    @bleat = Bleat.new
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @bleats = @user.bleats
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bleats_helper.rb
module BleatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/bleats/_bleats.html.erb
<% @bleats.reverse.each do |bleat| %>
  <%= link_to bleat.user.username, profile_path(bleat.user.id) %>
  <%= bleat.body %>
  <br>
<% end %>

app/views/bleats/_new-bleat.html.erb
<h3>Post a Bleat!</h3>
<p>Bleats must be no more than 280 characters</p>
<%= form_with model: [ @bleat ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/bleats/index.html.erb
<h1>Bleats#index</h1>
<p>Find me in app/views/bleats/index.html.erb</p>

app/views/bleats/new.html.erb
<div><%= render "bleats/new-bleat" %></div> <br> 

app/views/home/_header.html.erb
<ul>
  <li><%= link_to "Home", home_index_path %></li>
    <% if user_signed_in?%>
      <li><%= link_to "Bleat!", new_bleat_path %></li>
      <li><%= link_to "My Profile", profile_path(current_user.id) %></li>
      <li><%= link_to "All Profiles", profiles_path %></li>
      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In",  new_user_session_path %></li>
    <% end %>
</ul>

app/views/home/index.html.erb
<div>
  <h1>Welcome to Bleater.com</h1>
  <p>Whats on your mind?</p>
</div>
<% if user_signed_in?%>
  <div><%= render "bleats/new-bleat" %></div> <br> 
<% else %>
  <p><%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Sign In",  new_user_session_path %> to post your own Bleats!</p>
<% end %>
<div><%= render "bleats/bleats" %></div> <br> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bleater</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
      <div><%= render "home/header" %></div> <br> 
  </header>
  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>List of all profiles!</h1>
<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user.id) %>
<br>
<% end %>

app/views/profiles/show.html.erb
<% if @user == current_user%>
  <h5>Welcome to your profile!<h5>
<% else %>
  <h5>Welcome to <%= @user.username %>'s profile!</h5>
<% end %>

<% @user.bleats.reverse.each do |bleat| %>
  <%= link_to bleat.user.username, profile_path(bleat.user.id) %>
  <%= bleat.body %>
  <br>
<% end %>